

name: Check For Build

on:
  push:
    tags:
      - "*.*.*"

  workflow_dispatch:

jobs:

  linting:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setup Node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        
      # Build Dist for Distribution
      - name: Run and Build Dependency
        run: |
              npm install
              npm run build
      

